-- Project Spain relocation app — core schema.
-- Base tables are RLS-protected; only the editor (authenticated) may touch them.
-- The public catalogue is served through a view that exposes only safe columns,
-- so private notes and proposal state never reach anonymous visitors.

create extension if not exists pgcrypto;

-- ITEMS ---------------------------------------------------------------------
create table if not exists public.items (
  id           bigint generated by default as identity primary key,
  name         text        not null,
  cover        text        not null default '',
  photos       jsonb       not null default '[]'::jsonb,
  disposition  text        not null default 'keep'
               check (disposition in ('keep','sell','give','throw')),
  price_huf    integer,
  status       text        not null default 'available'
               check (status in ('available','reserved','gone')),
  published    boolean     not null default false,
  awaiting     boolean     not null default false,
  stamped      boolean     not null default true,
  proposed_by  text        check (proposed_by in ('Richard','Dorka')),
  private_note text,
  description  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- TASKS ---------------------------------------------------------------------
create table if not exists public.tasks (
  id          bigint generated by default as identity primary key,
  title       text        not null,
  phase       text        not null
              check (phase in ('Ügyintézés','Lakhatás','Iskola','Pénzügyek','Csomagolás','Általános')),
  assignee    text        not null default 'Both'
              check (assignee in ('Richard','Dorka','Both')),
  due         date,
  priority    text        not null default 'normal'
              check (priority in ('low','normal','high')),
  done        boolean     not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- keep updated_at fresh -----------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists items_touch on public.items;
create trigger items_touch before update on public.items
  for each row execute function public.touch_updated_at();

drop trigger if exists tasks_touch on public.tasks;
create trigger tasks_touch before update on public.tasks
  for each row execute function public.touch_updated_at();

-- RLS -----------------------------------------------------------------------
alter table public.items enable row level security;
alter table public.tasks enable row level security;

drop policy if exists items_editor_all on public.items;
create policy items_editor_all on public.items
  for all to authenticated using (true) with check (true);

drop policy if exists tasks_editor_all on public.tasks;
create policy tasks_editor_all on public.tasks
  for all to authenticated using (true) with check (true);

-- PUBLIC CATALOGUE VIEW -----------------------------------------------------
-- Only published Sell / Give items that are not gone, and only safe columns.
create or replace view public.public_items
with (security_invoker = false) as
  select id, name, cover, photos, disposition, price_huf, status, description, created_at
  from public.items
  where published = true
    and disposition in ('sell','give')
    and status <> 'gone';

grant select on public.public_items to anon, authenticated;

-- Realtime for quiet live collaboration between the two editors.
alter publication supabase_realtime add table public.items;
alter publication supabase_realtime add table public.tasks;
