-- Private note thread: append-only, author + timestamp, never public.
-- (Applied to the live project as migration `item_notes_thread`.)
create table if not exists public.item_notes (
  id         bigint generated by default as identity primary key,
  item_id    bigint      not null references public.items(id) on delete cascade,
  author     text        check (author in ('Richard','Dorka')),
  body       text        not null,
  created_at timestamptz not null default now()
);

create index if not exists item_notes_item_id_idx on public.item_notes (item_id);

alter table public.item_notes enable row level security;

drop policy if exists item_notes_editor_all on public.item_notes;
create policy item_notes_editor_all on public.item_notes
  for all to authenticated using (true) with check (true);

alter publication supabase_realtime add table public.item_notes;

-- One-time backfill: migrate any pre-existing single note into the thread
-- (author unknown → shown as "korábbi jegyzet"). The old items.private_note
-- column is kept but no longer read or written.
insert into public.item_notes (item_id, author, body, created_at)
select id, null, private_note, created_at
from public.items
where private_note is not null and btrim(private_note) <> '';
