-- Dobozok: numbered boxes with content photos. The row id IS the box number.
-- (Applied to the live project as migration `boxes_and_item_linking`.)
create table if not exists public.boxes (
  id         bigint generated by default as identity primary key,
  label      text        not null default '',
  room       text        not null default '',
  note       text        not null default '',
  sealed     boolean     not null default false,
  photos     jsonb       not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists boxes_touch on public.boxes;
create trigger boxes_touch before update on public.boxes
  for each row execute function public.touch_updated_at();

alter table public.boxes enable row level security;

drop policy if exists boxes_editor_all on public.boxes;
create policy boxes_editor_all on public.boxes
  for all to authenticated using (true) with check (true);

alter publication supabase_realtime add table public.boxes;

-- Visszük items can be packed into a box; deleting a box unpacks, never deletes.
alter table public.items
  add column if not exists box_id bigint references public.boxes(id) on delete set null;

create index if not exists items_box_id_idx on public.items (box_id);
